@baseUrl = http://localhost:8888
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlYjliY2EwYmFiYTJlMzA5MDZiNGJjMyIsImlhdCI6MTU4OTIzMTAxMCwiZXhwIjoxNTkxODIzMDEwfQ.XWDAy-ba5W3DgcGB4lq12QgpeH6_zwO9hfXxNi0aXUw
@userId = 


###

# @name loginUser 
// Login user
POST {{baseUrl}}/api/login HTTP/1.1
Content-Type: application/json

{
  "email":"chad.m.wittman75@gmail.com",
  "password":"password"
}

###

# @name CreateUser
// Register A User
POST  {{baseUrl}}/api/register HTTP/1.1
Content-Type: application/json

{
  "name": "chad",
  "email": "chad.m.wittman75@gmail.com",
  "password": "password"
}

###

# @name getMe
// get user from Bearer token
GET {{baseUrl}}/api/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name updateUser
// Update A user
PUT {{baseUrl}}/api/user HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "role":"admin"
}